# Generated by Django 3.1.12 on 2025-03-16 17:45

from django.db import migrations, models
import foodie_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='temp_images/', validators=[foodie_app.models.validate_image_size, foodie_app.models.validate_image_format])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'temporaryImages',
            },
        ),
    ]
