# Generated by Django 3.1.12 on 2025-11-25 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foodie_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_recipes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'generatedRecipes',
            },
        ),
    ]
