# Generated by Django 3.1.12 on 2025-12-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie_app', '0002_generatedrecipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('cookingTime', models.TextField()),
                ('ingredients', models.TextField()),
                ('instructions', models.TextField()),
                ('top_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'TopRecipes',
            },
        ),
        migrations.RenameField(
            model_name='generatedrecipe',
            old_name='content',
            new_name='cookingTime',
        ),
        migrations.AddField(
            model_name='generatedrecipe',
            name='ingredients',
            field=models.TextField(default='[]'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generatedrecipe',
            name='instructions',
            field=models.TextField(default='[]'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generatedrecipe',
            name='tag',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generatedrecipe',
            name='title',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temporaryimage',
            name='imageObjectId',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
