name: CI Pipeline

on:
  push:
    branches:
      - main
      - "feature-*"
  pull_request:
    branches:
      - main


jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python environment (based on your framework)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
