name:  TextField tests

on:
  push:
    branches:
      - feature-homesScreen

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r foodie/requirements.txt
          pip install pytest

      - name: Run tests
        env:
        DJANGO_SETTINGS_MODULE: foodie.settings
        PYTHONPATH: ${{ github.workspace }}/foodie
        run: |
          python -m pytest foodie/foodie_app/tests/test.py -v | tee test-results.txt

      - name: Save test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results.txt