name: uniTest pipeline

on:
  push:
    branches:
      - unitTest

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:latest
        options: --health-cmd "mongosh --eval 'db.serverStatus()'" --health-interval 10s --health-timeout 5s --health-retries 5
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r foodie/requirements.txt
          pip install pytest pytest-django
          pip install pytest

      - name: Run tests
        env:
          DJANGO_SETTINGS_MODULE: foodie.settings
          MONGO_HOST: localhost
          MONGO_PORT: 27017
          MONGO_USER: root
          MONGO_PASSWORD: example
        run: |
          PYTHONPATH=$GITHUB_WORKSPACE/foodie python -m pytest | tee test-results.txt

      - name: Save test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results.txt
