name: uniTest pipeline

on:
  push:
    branches:
      - unitTest

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r foodie/requirements.txt
          pip install pytest pytest-django
          pip install pytest

      - name: Start MongoDB
        run: |
          docker run --name mongodb -d -p 27017:27017 mongo:latest

      - name: Wait for MongoDB to be ready
        run: |
          until nc -zv localhost 27017; do
            echo "Waiting for MongoDB to start..."
            sleep 2
          done

      - name: Run tests
        run: |
          cd foodie  # Change to the foodie directory
          python -m pytest foodie_app/tests/test_photoUpload.py -v | tee test-results.txt

      - name: Save test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results.txt
